language: d

#compiler:
#  - dmd

install:
  # dmd
  - DMD_VERSION=2.064.2
  - RELEASE_YEAR=2013
  - wget http://downloads.dlang.org/releases/${RELEASE_YEAR}/dmd.${DMD_VERSION}.zip
  - unzip dmd.${DMD_VERSION}.zip

script:
  - ./dmd2/linux/bin64/dmd src/a.d -unittest

branches:
  only:
    - master

notifications:
  email: true
